#!/bin/bash

# Exports

#. $ANDROID_BUILD_TOP/vendor/aosp/tools/colors

OUT=$1

export Changelog=Changelog.txt

if [ -f $Changelog ];
then
	rm -f $Changelog
fi

touch $Changelog

# Print something to build output
echo ${bldppl}"Generating changelog..."${txtrst}

for i in $(seq 5);
do
export After_Date=$(date --date="$i days ago" +%m-%d-%Y 2>&1)
k=$(expr $i - 1)
	export Until_Date=$(date --date="$k days ago" +%m-%d-%Y 2>&1)

	# Line with after --- until was too long for a small ListView
	echo '====================' >> $Changelog;
	echo  "     "$Until_Date    >> $Changelog;
	echo '====================' >> $Changelog;
	# Cycle through every repo to find commits between 2 dates
	while read path;
		do
	CLOG=$(git --git-dir ./${path}/.git log --oneline --after=$After_Date --until=$Until_Date 2>&1);
	if [ -n "$CLOG" ]; then
		echo project $path >> $Changelog
		ret=$(git --git-dir ./${path}/.git log --oneline --after=$After_Date --until=$Until_Date 2>&1) >> $Changelog
	fi
	done < ./.repo/project.list
	echo >> $Changelog;
        echo >> $Changelog;
done

sed -i 's/project/   */g' $Changelog

cp $Changelog $OUT/system/etc/
cp $Changelog $OUT
rm $Changelog
