#!/bin/sh

# Exports

#. $ANDROID_BUILD_TOP/vendor/aosp/tools/colors

export Changelog=Changelog.txt

DEVICE=$(echo $TARGET_PRODUCT | sed -e 's/aosp_//g')

if [ -f $Changelog ];
then
	rm -f $Changelog
fi

touch $Changelog

for i in $(seq 5);
do
export After_Date=`/bin/date --date="$i days ago" +%m-%d-%Y`
k=$(expr $i - 1)
export Until_Date=`/bin/date --date="$k days ago" +%m-%d-%Y`
echo "====================" >> $Changelog;
echo "    $Until_Date     " >> $Changelog;
echo "====================" >> $Changelog;
# Cycle through every repo to find commits between 2 dates
while read path;
do
	CLOG=$(git --git-dir ./${path}/.git log --oneline --after=$After_Date --until=$Until_Date --pretty=tformat:"%h  %s  [%an]" --abbrev-commit --abbrev=7);
	if [ -n "$CLOG" ]; then
		echo "\n* ${path}\n${CLOG}\n" >> $Changelog;
	fi
done < ./.repo/project.list
echo "" >> $Changelog;
done

sed -i 's/project/   */g' $Changelog

cp $Changelog ./out/target/product/$DEVICE/system/etc/
cp $Changelog ./out/target/product/$DEVICE/
rm $Changelog
