#!/bin/bash
export PATH=/bin:$BIN:$PATH
set -e

usage() {
  cat <<EOM
  Usage: $(basename $0) <Path to output directory, typically \$OUT variable>
EOM
  exit 1
}

OUT="$1"

if [ ! -d "$OUT" ];then
  echo "specified OUT-directory: $OUT does not exist!"
  exit 1
fi

changelog="$OUT/Changelog.txt"
system_changelog="$OUT/system/etc/Changelog.txt"

# Print something to build output
echo ${bldppl}"Generating changelog..."${txtrst}

if [ -f "$changelog" ];
then
   rm -f "$changelog"
fi

touch $changelog
for i in $(seq 10);
do
    after_Date='date --date="$i days ago" +%m-%d-%Y'
    k=$((i - 1))
    until_Date=$'date --date="$k days ago" +%m-%d-%Y'

    # Line with after --- until was too long for a small ListView
    echo '====================' >> "$changelog";
    echo  "   "$until_Date      >> "$changelog";
    echo '====================' >> "$changelog";
    # Cycle through every repo to find commits between 2 dates
    CURRENT_PATH="$(realpath `pwd`)"

    repo forall -c "GIT_LOG=\`git log --oneline --after=$after_Date --until=$until_Date\` ; if [ ! -z \"\$GIT_LOG\" ]; then printf  '\n   * '; realpath \`pwd\` | sed 's|^$CURRENT_PATH/||' ; echo \"\$GIT_LOG\"; fi" >> "$changelog"
    echo >> "$changelog";
done

sed -i 's/project/   */g' "$changelog"

mkdir -p $(dirname "$system_changelog")
cp "$changelog" "$system_changelog"

exit 0
